# Generated by Django 5.1.1 on 2024-12-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multymessenger", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multymessenger",
            name="unique_id",
            field=models.CharField(max_length=36),
        ),
        migrations.AlterModelTable(
            name="multymessenger",
            table="messenger",
        ),
    ]
