# Generated by Django 5.1.1 on 2024-12-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multymessenger", "0006_alter_multymessenger_contact_num_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multymessenger",
            name="contact_num",
            field=models.TextField(),
        ),
    ]
