# Generated by Django 5.1.1 on 2024-12-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multymessenger", "0007_alter_multymessenger_contact_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="multymessenger",
            name="f_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="multymessenger",
            name="l_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="multymessenger",
            name="contact_num",
            field=models.CharField(max_length=15),
        ),
        migrations.AddIndex(
            model_name="multymessenger",
            index=models.Index(
                fields=["unique_id"], name="messenger_unique__96e064_idx"
            ),
        ),
    ]
